services: 
  api-gateway:
    build:
      context: .
    volumes:
      - .:/backend
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    restart: always
#    depends_on:
#      - postgres
    ports:
      - "8000:8000"    